---
- name: Deploy Backend Artifact
  synchronize: # "copy" takes too long!
    src: "../../backend/build"
    dest: ~/anyhasher

- name: Stop Server, if running
  pm2:
    name: server
    state: stopped

- name: Start Server
  shell: "cd ~/anyhasher/build && pm2 start server.js"

- name: Verify Server
  uri:
    url: http://localhost/hash/123
