---
- name: Deploy Backend Artifact
  synchronize: # "copy" takes too long!
    src: "../../backend/build"
    dest: ~/anyhasher

- name: Start Server
  shell: "cd ~/anyhasher/build && pm2 restart server.js"

- name: Verify Server
  uri:
    url: http://localhost/hash/123
