---
- name: Deploy Backend Artifact
  synchronize: # "copy" takes too long!
    src: "../../backend/build"
    dest: ~/anyhasher

- name: Start Server
  shell: "cd ~/anyhasher/build && pm2 start server.js -f" #force re-execution

- name: Verify Server
  uri:
    url: http://localhost:5001/hash/123
