name: Deploy Backend
run-name: "🚛 CD: Deploying Backend Artifact (${{ inputs.ref }})"
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      backend_host:
        required: true
        type: string
      backend_port:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_PRIVATE_KEY:
        required: true
    
jobs:
  deploy:
    name: 🚛 Deploy Backend Artifact
    runs-on: ubuntu-latest
    environment:
      name: Backend
      url: http://${{inputs.backend_host}}:${{inputs.backend_port}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact-${{ inputs.ref }}
          path: backend/build/
          
      - name: Configure Backend Infrastructure
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./util/ansible
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          inventory: |
            [ec2]
            ${{inputs.backend_host}} ansible_user=ubuntu
          # options: |
          #   --verbose

  verify:
    name: 🧪 Check Backend
    runs-on: ubuntu-latest
    needs: [deploy]
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Backend Smoke Test
        run: |
          export BACKEND_URL=http://${{inputs.backend_host}}:${{inputs.backend_port}}
          cd backend/e2e
          chmod +x backend-smoke.sh
          ./backend-smoke.sh

      #- name: Simulate an error
      #  run: exit 1  