name: Deploy Frontend
run-name: "🚛 CD: Deploying Frontend Artifact (${{ inputs.ref }})"
env:
  frontend_host: anyhasher-big-bang.s3-website-us-east-1.amazonaws.com
  frontend_bucket_name: anyhasher-big-bang
on:
  workflow_call:
    inputs:  
      ref:
        required: true
        type: string
      backend_url:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_PRIVATE_KEY:
        required: true
    outputs:
      frontend_url: 
        value: http://$frontend_host
      s3_bucket_hostname: 
        value: $frontend_host
      
jobs:
  deploy:
    name: 🚚 Deploy Frontend Artifact
    runs-on: ubuntu-latest
    environment:
      name: S3 Bucket Frontend
      url: $frontend_host
    steps:
      - name: Get Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact-${{ inputs.ref }}
          path: frontend/build

      - name: Prepare frontend with backend url
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: http://localhost:5000
          replace: ${{ inputs.backend_url }}
          
      - name: Store Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-release-${{ inputs.ref }}
          path: frontend/build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload frontend to S3 Bucket
        run: |
          aws s3 cp frontend/build s3://$frontend_bucket_name --region=us-east-1 --recursive

  verify:
    name: 🧪 Check Frontend
    needs: [deploy]
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL=http://$frontend_host
          cd frontend/e2e
          npm install
          npm run smoke