name: Big Bang CI/CD Pipeline
run-name: "🛠️ ${{ github.event.head_commit.message }} (${{ github.sha }})"
on:
  push: 
    branches:
      - big-bang-demo   #normally 'main'

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yml
    with:
      ref: ${{ github.sha }}    

  ci-backend:
    uses: ./.github/workflows/ci-backend.yml
    with:
      ref: ${{ github.sha }}    

  cd-backend:
    needs: [ci-frontend, ci-backend]
    uses: ./.github/workflows/cd-backend.yml
    with: 
      ref: ${{ github.sha }}    
    secrets: inherit

  cd-frontend:
    needs: [cd-backend]
    uses: ./.github/workflows/cd-frontend.yml
    with: 
      ref: ${{ github.sha }}    
      backend_url: ${{ needs.cd-backend.outputs.backend_url }}
    secrets: inherit